"""
SkillPatcher — generates diff-style patches for failing skills.

Patches are written to <workspace>/skills/patches/ awaiting review.
"""
from __future__ import annotations

import logging
import time
from pathlib import Path
from typing import Any

log = logging.getLogger("essence.skills.evolution.patch")


_PATCH_TEMPLATE = """\
# Skill Patch — {skill_name}

> Auto-generated patch from failure analysis.
> Episode: {episode_id}
> Root cause: {root_cause}
> Patched at: {patched_at}
> **Review required before applying.**

## Problem

{problem_description}

## Proposed Fix

{proposed_fix}

## Diff Instructions

Apply the following changes to `skills/{skill_name}/SKILL.md`:

```diff
{diff_content}
```

## Notes

This patch was automatically generated by SkillPatcher after observing
a failure in episode `{episode_id}`. Review and apply manually after
verifying the proposed fix is correct.
"""


class SkillPatcher:
    """
    Generates diff-style patches for failing skills.
    Patches are written to <workspace>/skills/patches/ awaiting review.

    Content generation (generate_patch_content) is separated from disk I/O
    (patch) so the SkillEvolutionSwitch can inspect content before writing.
    """

    def __init__(self,
                 workspace: Path | None = None,
                 router: Any = None) -> None:
        self._workspace = workspace
        self._router    = router

    def generate_patch_content(self, episode: Any) -> str:
        """
        Generate the patch Markdown WITHOUT writing to disk.

        Used by ReflectionSkill + SkillEvolutionSwitch so the content can be
        reviewed (by model verifier or human) before being committed.

        Returns the raw Markdown string.
        """
        episode_id          = str(getattr(episode, "id", "unknown"))
        task                = getattr(episode, "task", None)
        skill_name          = str(getattr(task, "goal", "unknown"))[:40]
        result              = getattr(episode, "result", None)
        notes               = str(getattr(result, "notes", "No details available"))
        root_cause          = self._infer_root_cause(notes)
        problem_description = f"Failure notes: {notes[:500]}"
        proposed_fix        = self._generate_fix(root_cause, notes)
        diff_content        = self._generate_diff(skill_name, notes)
        return _PATCH_TEMPLATE.format(
            skill_name          = skill_name,
            episode_id          = episode_id,
            root_cause          = root_cause,
            patched_at          = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
            problem_description = problem_description,
            proposed_fix        = proposed_fix,
            diff_content        = diff_content,
        )

    def patch(self, episode: Any) -> Path | None:
        """
        Generate a patch for the skill involved in a failed episode.

        Returns the path to the generated patch file, or None on failure.
        """
        if self._workspace is None:
            log.warning("skill_patcher_no_workspace")
            return None

        patches_dir = self._workspace / "skills" / "patches"
        patches_dir.mkdir(parents=True, exist_ok=True)

        episode_id  = str(getattr(episode, "id", "unknown"))
        task        = getattr(episode, "task", None)
        skill_name  = str(getattr(task, "goal", "unknown"))[:40]
        result      = getattr(episode, "result", None)
        notes       = str(getattr(result, "notes", "No details available"))
        root_cause  = self._infer_root_cause(notes)

        patch_name = f"patch-{episode_id[:8]}-{int(time.time())}.md"
        patch_path = patches_dir / patch_name

        problem_description = f"Failure notes: {notes[:500]}"
        proposed_fix        = self._generate_fix(root_cause, notes)
        diff_content        = self._generate_diff(skill_name, notes)

        content = _PATCH_TEMPLATE.format(
            skill_name=skill_name,
            episode_id=episode_id,
            root_cause=root_cause,
            patched_at=time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime()),
            problem_description=problem_description,
            proposed_fix=proposed_fix,
            diff_content=diff_content,
        )

        patch_path.write_text(content, encoding="utf-8")
        log.info("skill_patch_written",
                 extra={"path": str(patch_path), "episode": episode_id})
        return patch_path

    def _infer_root_cause(self, notes: str) -> str:
        n = notes.lower()
        if any(w in n for w in ("timeout", "network", "connection")):
            return "transient_error"
        if any(w in n for w in ("permission", "access denied")):
            return "permission_error"
        if any(w in n for w in ("not found", "404", "missing")):
            return "missing_resource"
        return "logic_error"

    def _generate_fix(self, root_cause: str, notes: str) -> str:
        fixes = {
            "transient_error":  "Add retry logic with exponential backoff for transient failures.",
            "permission_error": "Check and update required permissions in the skill configuration.",
            "missing_resource": "Add validation for required resources before execution.",
            "logic_error":      "Review the skill implementation for logic errors based on failure notes.",
        }
        return fixes.get(root_cause, "Review and fix the skill implementation.")

    def _generate_diff(self, skill_name: str, notes: str) -> str:
        return (
            f"--- a/skills/{skill_name}/SKILL.md\n"
            f"+++ b/skills/{skill_name}/SKILL.md\n"
            f"@@ SKILL BODY @@\n"
            f"- # Current implementation (review required)\n"
            f"+ # Updated implementation\n"
            f"+ # Fix: {self._generate_fix(self._infer_root_cause(notes), notes)}\n"
        )
