"""DailyBriefingEngine — generates a personalised morning digest.

Aggregates from TemporalPlane, PersonalTwin, CognitiveHealthMonitor,
UserPreferenceEngine, and OpportunityEngine into a single morning summary.

Wire into HeartbeatScheduler as a cron job (default: daily at 07:00).
The briefing is written to <workspace>/logs/daily_briefing.md and also
published as a ProactiveEvent via the event_bus.
"""
from __future__ import annotations

import dataclasses
import json
import logging
import time
from pathlib import Path
from typing import Any

log = logging.getLogger("essence.intelligence.daily_briefing")


@dataclasses.dataclass
class DailyBriefing:
    """Structured morning digest."""
    generated_at:     float
    date_str:         str
    pending_goals:    list[dict]         # from TemporalPlane
    stale_projects:   list[str]         # from memory
    cognitive_score:  str               # healthy / degraded / unknown
    cognitive_alerts: list[str]
    top_domains:      list[str]         # from UserPreferenceEngine
    opportunities:    list[dict]        # from OpportunityEngine
    reminders_due:    list[str]         # from ReminderEngine
    research_digests: list[str]         # from AutonomousResearchEngine

    def to_markdown(self) -> str:
        lines = [
            f"# 🌅 Daily Briefing — {self.date_str}",
            "",
        ]

        # Cognitive health
        icon = "✅" if self.cognitive_score == "healthy" else "⚠️"
        lines.append(f"## {icon} Cognitive Health: {self.cognitive_score.title()}")
        for alert in self.cognitive_alerts:
            lines.append(f"  - {alert}")
        lines.append("")

        # Active goals
        if self.pending_goals:
            lines.append("## 🎯 Active Goals")
            for g in self.pending_goals:
                horizon = g.get("horizon", "?")
                desc    = g.get("description", "")[:120]
                lines.append(f"  - **[{horizon}]** {desc}")
            lines.append("")

        # Stale projects
        if self.stale_projects:
            lines.append("## 🗂 Stale Projects (need attention)")
            for p in self.stale_projects:
                lines.append(f"  - {p}")
            lines.append("")

        # Due reminders
        if self.reminders_due:
            lines.append("## 🔔 Due Today")
            for r in self.reminders_due:
                lines.append(f"  - {r}")
            lines.append("")

        # Opportunities
        if self.opportunities:
            lines.append("## ⚡ Opportunities")
            for opp in self.opportunities[:3]:
                lines.append(f"  - {opp.get('suggestion', opp.get('domain', ''))}")
            lines.append("")

        # Top interest domains
        if self.top_domains:
            lines.append(f"## 📚 Your Top Domains: {', '.join(self.top_domains)}")
            lines.append("")

        # Research digests
        if self.research_digests:
            lines.append("## 🔬 Research Updates")
            for d in self.research_digests[:3]:
                lines.append(f"  - {d}")
            lines.append("")

        lines.append("---")
        lines.append("_Generated by Essence DailyBriefingEngine_")
        return "\n".join(lines)

    def to_dict(self) -> dict:
        return dataclasses.asdict(self)


class DailyBriefingEngine:
    """
    Generates a personalised morning digest aggregating all intelligence
    subsystems.

    Integration points
    ------------------
    Boot       : instantiated after all intelligence modules; receives refs
    Heartbeat  : register via heartbeat.add("daily_briefing", ..., "cron:0 7 * * *")
                 and call generate() from the job message handler
    """

    def __init__(
        self,
        workspace:       Path,
        temporal:        Any = None,
        twin:            Any = None,
        cognitive_health: Any = None,
        user_preference: Any = None,
        opportunity:     Any = None,
        reminder:        Any = None,
        research:        Any = None,
        event_bus:       Any = None,
    ) -> None:
        self._ws      = workspace
        self._temporal       = temporal
        self._twin           = twin
        self._cog_health     = cognitive_health
        self._user_pref      = user_preference
        self._opportunity    = opportunity
        self._reminder       = reminder
        self._research       = research
        self._bus            = event_bus
        self._log_path       = workspace / "logs" / "daily_briefing.md"
        self._log_path.parent.mkdir(parents=True, exist_ok=True)

    # ── public API ────────────────────────────────────────────────────────────

    def generate(self) -> DailyBriefing:
        """Build and return today's briefing. Also writes it to disk and publishes."""
        now      = time.time()
        date_str = time.strftime("%Y-%m-%d", time.localtime(now))

        pending_goals    = self._collect_goals()
        stale_projects   = self._collect_stale_projects()
        cog_score, cog_alerts = self._collect_cognitive()
        top_domains      = self._collect_top_domains()
        opportunities    = self._collect_opportunities()
        reminders_due    = self._collect_reminders_due()
        research_digests = self._collect_research()

        briefing = DailyBriefing(
            generated_at    = now,
            date_str        = date_str,
            pending_goals   = pending_goals,
            stale_projects  = stale_projects,
            cognitive_score = cog_score,
            cognitive_alerts= cog_alerts,
            top_domains     = top_domains,
            opportunities   = opportunities,
            reminders_due   = reminders_due,
            research_digests= research_digests,
        )

        md = briefing.to_markdown()
        try:
            self._log_path.write_text(md, encoding="utf-8")
            log.info("daily_briefing_written", extra={"path": str(self._log_path)})
        except Exception as exc:
            log.debug("daily_briefing_write_error: %s", exc)

        self._publish(briefing)
        return briefing

    def latest(self) -> str:
        """Return the markdown of the most recently generated briefing."""
        if self._log_path.exists():
            try:
                return self._log_path.read_text(encoding="utf-8")
            except Exception:
                pass
        return "_No briefing generated yet._"

    # ── collectors ────────────────────────────────────────────────────────────

    def _collect_goals(self) -> list[dict]:
        if self._temporal is None:
            return []
        try:
            return self._temporal.all_goals()[:10]
        except Exception as exc:
            log.debug("briefing_goals_error: %s", exc)
            return []

    def _collect_stale_projects(self) -> list[str]:
        stale: list[str] = []
        try:
            proj_file = self._ws / "ongoing_projects.json"
            if proj_file.exists():
                projects = json.loads(proj_file.read_text(encoding="utf-8"))
                now = time.time()
                cutoff = now - 7 * 86400
                for name, info in list(projects.items())[:10]:
                    last = info.get("last_updated", 0) if isinstance(info, dict) else 0
                    if last < cutoff:
                        days = int((now - last) / 86400)
                        stale.append(f"{name} ({days}d ago)")
        except Exception as exc:
            log.debug("briefing_projects_error: %s", exc)
        return stale

    def _collect_cognitive(self) -> tuple[str, list[str]]:
        if self._cog_health is None:
            return "unknown", []
        try:
            report = self._cog_health.assess()
            score  = "healthy" if report.is_healthy() else "degraded"
            return score, list(report.alerts)
        except Exception as exc:
            log.debug("briefing_cognitive_error: %s", exc)
            return "unknown", []

    def _collect_top_domains(self) -> list[str]:
        if self._user_pref is None:
            return []
        try:
            return self._user_pref.profile().top_domains(5)
        except Exception as exc:
            log.debug("briefing_domains_error: %s", exc)
            return []

    def _collect_opportunities(self) -> list[dict]:
        if self._opportunity is None:
            return []
        try:
            return self._opportunity.active_hints()[:5]
        except Exception as exc:
            log.debug("briefing_opportunities_error: %s", exc)
            return []

    def _collect_reminders_due(self) -> list[str]:
        if self._reminder is None:
            return []
        try:
            now    = time.time()
            eod    = now + 86400   # within next 24 h
            due    = [r for r in self._reminder.list_reminders(enabled_only=True)
                      if r.fire_at <= eod]
            return [f"{r.title}: {r.body[:80]}" for r in due[:5]]
        except Exception as exc:
            log.debug("briefing_reminders_error: %s", exc)
            return []

    def _collect_research(self) -> list[str]:
        if self._research is None:
            return []
        try:
            digests = self._research.run_cycle()
            return [d.to_proactive_body()[:120] for d in digests[:3]]
        except Exception as exc:
            log.debug("briefing_research_error: %s", exc)
            return []

    def _publish(self, briefing: DailyBriefing) -> None:
        """Publish briefing as a ProactiveEvent via the event_bus."""
        if self._bus is None:
            return
        try:
            from essence.agents.proactive import WebhookEvent
            evt = WebhookEvent(
                source="briefing",
                event_type="daily_ready",
                payload={
                    "date":            briefing.date_str,
                    "cognitive_score": briefing.cognitive_score,
                    "pending_goals":   len(briefing.pending_goals),
                    "reminders":       len(briefing.reminders_due),
                    "opportunities":   len(briefing.opportunities),
                },
            )
            pub = getattr(self._bus, "publish", None)
            if callable(pub):
                pub(evt)
        except Exception as exc:
            log.debug("briefing_publish_error: %s", exc)


def register_briefing_job(scheduler: Any, briefing_engine: "DailyBriefingEngine",
                           workspace: Path) -> None:
    """Register the daily briefing job with the HeartbeatScheduler."""
    schedule = "0 7 * * *"
    sentinel = f"_briefing_trigger:{workspace}"
    scheduler.add(
        name="daily_briefing",
        message=sentinel,
        schedule=schedule,
    )
    log.info("daily_briefing_job_registered", extra={"schedule": schedule})
